spring.application.name=jobberdb

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

app.frontend.base-url=http://localhost:5173
app.mail.from-name=JobLithic
app.mail.otp-expiry-minutes=10


server.port=8080

logging.level.org.hibernate.SQL=warn
logging.level.org.hibernate.orm.jdbc.bind=warn

app.ai.gemini.enabled=true
app.ai.gemini.base-url=https://generativelanguage.googleapis.com/v1beta/models
app.ai.gemini.model=gemini-2.5-flash
app.ai.gemini.api-key=${APIKEY}
